# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/GPIO.xdc

# Block Designs: bd/zynq/zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_blk_mem_gen_0_0/zynq_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_mem_gen_0_0 || ORIG_REF_NAME==zynq_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_bram_ctrl_0_1/zynq_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_bram_ctrl_0_1 || ORIG_REF_NAME==zynq_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_bram_ctrl_1_0/zynq_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_bram_ctrl_1_0 || ORIG_REF_NAME==zynq_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_smartconnect_0_0/zynq_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_smartconnect_0_0 || ORIG_REF_NAME==zynq_smartconnect_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_smartconnect_1_0/zynq_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_smartconnect_1_0 || ORIG_REF_NAME==zynq_smartconnect_1_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_cdma_0_0 || ORIG_REF_NAME==zynq_axi_cdma_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_proc_sys_reset_0_0/zynq_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_gpio_lab_1_0_1/zynq_gpio_lab_1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_gpio_lab_1_0_1 || ORIG_REF_NAME==zynq_gpio_lab_1_0_1} -quiet] -quiet

# XDC: bd/zynq/zynq_ooc.xdc
