# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.cache/wt [current_project]
set_property parent.project_path /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/ecelrc/students/gguglielmo/micro/vivado/ip_repo/gpio_lab_1_1.0 [current_project]
set_property ip_output_repo /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/hdl/zynq_wrapper.v
add_files /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/zynq.bd
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_blk_mem_gen_0_0/zynq_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_bram_ctrl_0_1/zynq_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_bram_ctrl_1_0/zynq_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_10/bd_2d56_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_16/bd_2d56_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_23/bd_2d56_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_30/bd_2d56_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_31/bd_2d56_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_32/bd_2d56_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_33/bd_2d56_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_34/bd_2d56_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_35/bd_2d56_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_24/bd_2d56_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_25/bd_2d56_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_26/bd_2d56_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_27/bd_2d56_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_28/bd_2d56_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_17/bd_2d56_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_18/bd_2d56_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_19/bd_2d56_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_20/bd_2d56_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_21/bd_2d56_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_11/bd_2d56_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_12/bd_2d56_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_13/bd_2d56_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_14/bd_2d56_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_15/bd_2d56_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_2/bd_2d56_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_3/bd_2d56_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_4/bd_2d56_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_5/bd_2d56_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_6/bd_2d56_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_10/bd_ed07_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_16/bd_ed07_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_23/bd_ed07_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_24/bd_ed07_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_25/bd_ed07_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_26/bd_ed07_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_27/bd_ed07_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_28/bd_ed07_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_17/bd_ed07_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_18/bd_ed07_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_19/bd_ed07_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_20/bd_ed07_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_21/bd_ed07_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_11/bd_ed07_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_12/bd_ed07_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_13/bd_ed07_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_14/bd_ed07_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_15/bd_ed07_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_2/bd_ed07_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_3/bd_ed07_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_4/bd_ed07_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_5/bd_ed07_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_6/bd_ed07_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_proc_sys_reset_0_0/zynq_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_proc_sys_reset_0_0/zynq_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_proc_sys_reset_0_0/zynq_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/zynq_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/constrs_1/new/GPIO.xdc
set_property used_in_implementation false [get_files /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/constrs_1/new/GPIO.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zynq_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zynq_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zynq_wrapper_utilization_synth.rpt -pb zynq_wrapper_utilization_synth.pb"
