# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/zynq_smartconnect_0_0.xci
# IP: The module: 'zynq_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/bd_2d56.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_10/bd_2d56_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_16/bd_2d56_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_23/bd_2d56_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_30/bd_2d56_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_36/bd_2d56_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_31/bd_2d56_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_32/bd_2d56_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_33/bd_2d56_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_34/bd_2d56_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_35/bd_2d56_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_29/bd_2d56_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_24/bd_2d56_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_25/bd_2d56_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_26/bd_2d56_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_27/bd_2d56_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_28/bd_2d56_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_22/bd_2d56_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_17/bd_2d56_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_18/bd_2d56_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_19/bd_2d56_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_20/bd_2d56_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_21/bd_2d56_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_11/bd_2d56_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_12/bd_2d56_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_13/bd_2d56_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_14/bd_2d56_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_15/bd_2d56_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_7/bd_2d56_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_8/bd_2d56_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_9/bd_2d56_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_2/bd_2d56_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_3/bd_2d56_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_4/bd_2d56_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_5/bd_2d56_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_6/bd_2d56_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_0/bd_2d56_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_10/bd_2d56_s00a2s_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_16/bd_2d56_m00s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_23/bd_2d56_m01s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_30/bd_2d56_m02s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_31/bd_2d56_m02arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_32/bd_2d56_m02rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_33/bd_2d56_m02awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_34/bd_2d56_m02wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_35/bd_2d56_m02bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_24/bd_2d56_m01arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_25/bd_2d56_m01rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_26/bd_2d56_m01awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_27/bd_2d56_m01wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_28/bd_2d56_m01bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_17/bd_2d56_m00arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_18/bd_2d56_m00rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_19/bd_2d56_m00awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_20/bd_2d56_m00wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_21/bd_2d56_m00bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_11/bd_2d56_sarn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_12/bd_2d56_srn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_13/bd_2d56_sawn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_14/bd_2d56_swn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_15/bd_2d56_sbn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_2/bd_2d56_arsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_3/bd_2d56_rsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_4/bd_2d56_awsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_5/bd_2d56_wsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_6/bd_2d56_bsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/zynq_smartconnect_0_0.xci
# IP: The module: 'zynq_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/bd_2d56.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_10/bd_2d56_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_16/bd_2d56_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_23/bd_2d56_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_30/bd_2d56_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_36/bd_2d56_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_31/bd_2d56_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_32/bd_2d56_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_33/bd_2d56_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_34/bd_2d56_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_35/bd_2d56_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_29/bd_2d56_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_24/bd_2d56_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_25/bd_2d56_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_26/bd_2d56_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_27/bd_2d56_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_28/bd_2d56_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_22/bd_2d56_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_17/bd_2d56_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_18/bd_2d56_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_19/bd_2d56_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_20/bd_2d56_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_21/bd_2d56_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_11/bd_2d56_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_12/bd_2d56_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_13/bd_2d56_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_14/bd_2d56_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_15/bd_2d56_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_7/bd_2d56_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_8/bd_2d56_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_9/bd_2d56_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_2/bd_2d56_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_3/bd_2d56_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_4/bd_2d56_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_5/bd_2d56_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_6/bd_2d56_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_0/bd_2d56_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_10/bd_2d56_s00a2s_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_16/bd_2d56_m00s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_23/bd_2d56_m01s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_30/bd_2d56_m02s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_31/bd_2d56_m02arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_32/bd_2d56_m02rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_33/bd_2d56_m02awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_34/bd_2d56_m02wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_35/bd_2d56_m02bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_24/bd_2d56_m01arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_25/bd_2d56_m01rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_26/bd_2d56_m01awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_27/bd_2d56_m01wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_28/bd_2d56_m01bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_17/bd_2d56_m00arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_18/bd_2d56_m00rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_19/bd_2d56_m00awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_20/bd_2d56_m00wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_21/bd_2d56_m00bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_11/bd_2d56_sarn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_12/bd_2d56_srn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_13/bd_2d56_sawn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_14/bd_2d56_swn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_15/bd_2d56_sbn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_2/bd_2d56_arsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_3/bd_2d56_rsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_4/bd_2d56_awsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_5/bd_2d56_wsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_6/bd_2d56_bsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/bd_0/ip/ip_1/bd_2d56_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
