# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/zynq_smartconnect_1_0.xci
# IP: The module: 'zynq_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/bd_ed07.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_10/bd_ed07_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_16/bd_ed07_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_23/bd_ed07_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_29/bd_ed07_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_24/bd_ed07_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_25/bd_ed07_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_26/bd_ed07_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_27/bd_ed07_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_28/bd_ed07_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_22/bd_ed07_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_17/bd_ed07_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_18/bd_ed07_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_19/bd_ed07_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_20/bd_ed07_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_21/bd_ed07_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_11/bd_ed07_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_12/bd_ed07_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_13/bd_ed07_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_14/bd_ed07_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_15/bd_ed07_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_7/bd_ed07_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_8/bd_ed07_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_9/bd_ed07_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_2/bd_ed07_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_3/bd_ed07_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_4/bd_ed07_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_5/bd_ed07_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_6/bd_ed07_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_0/bd_ed07_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_10/bd_ed07_s00a2s_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_16/bd_ed07_m00s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_23/bd_ed07_m01s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_24/bd_ed07_m01arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_25/bd_ed07_m01rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_26/bd_ed07_m01awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_27/bd_ed07_m01wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_28/bd_ed07_m01bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_17/bd_ed07_m00arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_18/bd_ed07_m00rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_19/bd_ed07_m00awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_20/bd_ed07_m00wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_21/bd_ed07_m00bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_11/bd_ed07_sarn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_12/bd_ed07_srn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_13/bd_ed07_sawn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_14/bd_ed07_swn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_15/bd_ed07_sbn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_2/bd_ed07_arsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_3/bd_ed07_rsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_4/bd_ed07_awsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_5/bd_ed07_wsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_6/bd_ed07_bsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/zynq_smartconnect_1_0.xci
# IP: The module: 'zynq_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/bd_ed07.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_10/bd_ed07_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_16/bd_ed07_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_23/bd_ed07_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_29/bd_ed07_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_24/bd_ed07_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_25/bd_ed07_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_26/bd_ed07_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_27/bd_ed07_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_28/bd_ed07_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_22/bd_ed07_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_17/bd_ed07_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_18/bd_ed07_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_19/bd_ed07_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_20/bd_ed07_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_21/bd_ed07_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_11/bd_ed07_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_12/bd_ed07_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_13/bd_ed07_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_14/bd_ed07_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_15/bd_ed07_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_7/bd_ed07_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_8/bd_ed07_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_9/bd_ed07_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_2/bd_ed07_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_3/bd_ed07_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_4/bd_ed07_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_5/bd_ed07_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_6/bd_ed07_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_0/bd_ed07_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_10/bd_ed07_s00a2s_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_16/bd_ed07_m00s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_23/bd_ed07_m01s2a_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_24/bd_ed07_m01arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_25/bd_ed07_m01rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_26/bd_ed07_m01awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_27/bd_ed07_m01wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_28/bd_ed07_m01bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_17/bd_ed07_m00arn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_18/bd_ed07_m00rn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_19/bd_ed07_m00awn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_20/bd_ed07_m00wn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_21/bd_ed07_m00bn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_11/bd_ed07_sarn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_12/bd_ed07_srn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_13/bd_ed07_sawn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_14/bd_ed07_swn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_15/bd_ed07_sbn_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_2/bd_ed07_arsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_3/bd_ed07_rsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_4/bd_ed07_awsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_5/bd_ed07_wsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_6/bd_ed07_bsw_0_ooc.xdc

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/bd_0/ip/ip_1/bd_ed07_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
