# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0.xci
# IP: The module: 'zynq_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0.xci
# IP: The module: 'zynq_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ecelrc/students/gguglielmo/micro/vivado/lab_1/lab_1.srcs/sources_1/bd/zynq/ip/zynq_axi_cdma_0_0/zynq_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
